twitter: "TwitterApp"

port: 8080

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "n123456N"
  name: "twitter_db"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  accessKeyID: "admin"
  secretAccessKey: "admin123"
  useSSL: false
  bucketName: "testbucket"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"