twitter: "TwitterApp"

port: 8080

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "n123456N"
  name: "twitter_db"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

apikey: "re_MzT3hsTe_F4JTUCmausSEMkipw2tC7QwT"

secretkey: "your_secret_key"